version: '3.1'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/html
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Admin_0123
      MYSQL_DATABASE: secure_shop
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
